site_name: Tuteja Lab Wiki
site_url: https://tuteja-lab.readthedocs.io
site_description: Project documentation with Markdown.
site_author: Arun Seetharam

repo_url: https://github.com/aseetharam/tuteja-lab
edit_uri: ""

theme:
    name: readthedocs
    locale: en
    analytics: {gtag: ''}
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - django

