site_name: Tuteja Lab Wiki
site_url: https://tuteja-lab.readthedocs.io
site_description: Project documentation with Markdown.
site_author: Arun Seetharam

repo_url: https://github.com/aseetharam/tuteja-lab
edit_uri: ""

theme:
    name: readthedocs
    locale: en
    analytics: {gtag: ''}
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - django
nav:
    - Home: index.md
    - HPC setup:
        - Overview: hpc-setup/index.md
        - Installation: hpc-setup/dot-files.md
    - R setup:
        - Overview: using-r/index.md
        - R-Studio: using-r/singularity-r.md
